### ISSUE TITLE
Missing annotations?

### ISSUE THREAD

**Issue by oriondollar** [lfoppiano/SuperMat#2]
Hi there,

I'd like to use this task as part of an evaluation suite for a chemistry-specific natural language model. Other than the `SuperMat-1.0.csv` file in `data/csv` I'm not seeing where the annotations are being stored. In the paper you refer to an annotated structure within the xml files, however I'm not seeing any data within the text nodes for any of the xml files you've included in the repo. Am I missing or misunderstanding something?

<img width="475" alt="Screen Shot 2021-11-15 at 12 27 05 PM" src="https://user-images.githubusercontent.com/35129207/141849135-768da430-0d85-4410-be72-a3dba8bd261f.png">

**Comment by lfoppiano** [comment]
Dear @oriondollar, thanks for your interest in supermat. 
Unfortunately the XML files are not in this repository for copyright reasons. 
We though we could add to github only the annotations, but without the text makes them difficult to use (one could re-generate the text extracting from the original PDFs). 

I suggest that you send me an email (email in the paper) so that we can discuss this matter.
